### ISSUE TITLE
请教问题，为什么这里要+1？

### ISSUE THREAD

**Issue by vuchan** [musicq/vist#3]
@musicq 你好，在看你的源码发现在复用DOM的算法处有一个小 trick。但是不明所以，故向你请教：

Q1: 为什么这里要 `+1` 呢？

我试着改了一下此处，发现如果不 `+1` 在往回滚 1 个 `option.height` 的时候 `getDifferenceIndexes` 函数工作不正确，返回的数组为 `[]`。

[code](https://github.com/musicq/vist/blob/master/src/VirtualList.tsx#L175)
```ts
return (this.stateDataSnapshot = data.slice(firstIndex, lastIndex + 1).map(item => ({
```

[code1](https://github.com/musicq/vist/blob/master/src/VirtualList.tsx#L184)
```ts
let newIndex = dir > 0 ? lastIndex - diffSliceIndexes.length + 1 /* down */: firstIndex /* up */;
```

Q2: 为什么 +1 就可以正常工作了呢？
如果你能在百忙中回复，这也许能够帮助晚辈很快理解这个 trick 用法的原因。

代码经过这样的修改后工作正常，不用 +1 也正确 diff index。
```js
const newIndexes = new Array(endIndex - startIndex)
        .fill(startIndex)
        .map((i, d) => i + d);
      const diffIndexes = pool.reduce((acc, cur, idx) => {
        if (!newIndexes.includes(cur.$pos)) {
          acc[acc.length] = idx;
        }

        return acc;
      }, []);
```

另，觉得这个 重用DOM  `getDifferenceIndexes`的算法非常的实惠，非常感谢。

**Comment by musicq** [comment]
Hi,  @vuchan 

`+1` `-1` 只是为了校正索引的位置，比如第一个 `+1`

```javascript
[0,1,2,3].slice(0,3) // [0,1,2]

[0,1,2,3].slice(0,3+1) // [0,1,2,3]
```

**Comment by vuchan** [comment]
谢谢回复，谢谢开源。
